services:
  mysql:
    image: mysql:8.3
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'Bhavani@1984'
      MYSQL_USER: 'rohith'
      MYSQL_PASSWORD: 'Bhavani@1984'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'Bhavani@1984'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  userinfo_kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: userinfo_kafka
    container_name: userinfo_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@userinfo_kafka:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'PLAINTEXT://userinfo_kafka:29092,CONTROLLER://userinfo_kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://userinfo_kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    healthcheck:
      test: ["CMD-SHELL","kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  auth-service:
    build: ./authservice
    container_name: auth-service
    ports:
      - "9898:9898"
    depends_on:
      - mysql
      - userinfo_kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: authservice
      MYSQL_USER: rohith
      MYSQL_PASSWORD: 'Bhavani@1984'
      KAFKA_HOST: userinfo_kafka
      KAFKA_PORT: 29092

  user-service:
    build: ./userservice
    container_name: user-service
    ports:
      - "9810:9810"
    depends_on:
      - mysql
      - userinfo_kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
      MYSQL_USER: rohith
      MYSQL_PASSWORD: 'Bhavani@1984'
      KAFKA_HOST: userinfo_kafka
      KAFKA_PORT: 29092
  expense-service:
    build: ./expenseservice
    container_name: expense-service
    ports:
      - "9821:9821"
    depends_on:
      - mysql
      - userinfo_kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expenseservice
      MYSQL_USER: rohith
      MYSQL_PASSWORD: 'Bhavani@1984'
      KAFKA_HOST: userinfo_kafka
      KAFKA_PORT: 29092

  ds-service:
    build: ./dsservice
    container_name: ds-service
    ports:
      - "9820:9820"
    depends_on:
      mysql:
        condition: service_healthy
      userinfo_kafka:
        condition: service_healthy
      expense-service:
        condition: service_started
      user-service:
        condition: service_started
    environment:
      KAFKA_HOST: userinfo_kafka
      KAFKA_PORT: 29092
      MISTRAL_API_KEY: h025ypfW2b3p9aNaG8bDrz8obmMt529L
  
  kong-service:
    build:
      context: ./kong
      dockerfile: Dockerfile
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_LOG_LEVEL: "debug"
      KONG_PLUGINS: "custom-auth"
      KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:7990:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"

volumes:
  mysql_data:
